### ISSUE TITLE
Add Contributors Avatar to README.md

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-json-to-joi#2]
We would want to show contributors avatar in our README.md file.

This piece of code needs to be added in the README.md file bottom, with the title something like this

https://github.com/arshadkazmi42/ak-logger#contributors

`[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/images/0)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/links/0)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/images/1)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/links/1)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/images/2)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/links/2)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/images/3)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/links/3)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/images/4)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/links/4)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/images/5)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/links/5)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/images/6)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/links/6)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/images/7)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/ak-json-to-joi/links/7)`

**Comment by versavale** [comment]
Hi! Would like to give it a try.

**Comment by arshadkazmi42** [comment]
@versavale Awesome. Thanks
Go ahead and create a PR

**Comment by arshadkazmi42** [comment]
@versavale Thank you for working on this
