### ISSUE TITLE
Add Code Quality Badge

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-json-to-joi#32]
Add Code Quality badge next to downloads badge in README file

just copy the below code and add it in readme below downloads code

`[![Codacy Badge](https://api.codacy.com/project/badge/Grade/ad662a16b8784785b4d39b10f075a47c)](https://www.codacy.com/app/arshadkazmi42/ak-json-to-joi?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=arshadkazmi42/ak-json-to-joi&amp;utm_campaign=Badge_Grade)`

**To work on this**

1. Put a comment here who ever is working on it.
2. Also tag this issue in your Pull Request description.

_**Note:** Anyone who is not following above two steps, their PR will be rejected_

**Comment by dhoeric** [comment]
Hi @arshadkazmi42, I can work on this issue!

**Comment by EnzoDevelop** [comment]
I got this one
