### ISSUE TITLE
Fix broken link in Contributors.md

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-json-to-joi#44]
There is a Contributor added with wrong syntax in this file

https://github.com/arshadkazmi42/ak-json-to-joi/blob/master/Contributors.md

This needs to be fixed.

**Steps to work on the issue**

1. Comment here (eg: I am working on this or something like that)
2. Create PR.
3. Add this in your PR description `Closes #44` (Note: This should not go as a commit message.)
4. Do not work on forked master branch. Create a new branch when working on this.

**Note:** whoever comments here, gets the issue. Also if someone has taken the issue, do not create duplicate PRs

**Comment by ShahSheel** [comment]
Sure, i'll fix this

**Comment by PavanGangireddy** [comment]
Shall i work in it? @ShahSheel

**Comment by PavanGangireddy** [comment]
Ok cool
